version: '3'
services:
  app:
    build:
      context: .
    image: release
    command: ["yarn", "run", "start"]
    environment:
      - NODE_ENV=production
    ports:
      - '8080:8080'
    healthcheck:
      test: curl --fail -s http://localhost:8080 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
